
name: docker build

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Get image tag
      id: tags
      run: echo "::set-output name=tag::$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          rdbox/${{ env.CI_REPOSITORY_NAME }}:${{ steps.tags.outputs.tag }}
          rdbox/${{ env.CI_REPOSITORY_NAME }}:latest